# Generated by Django 5.0.2 on 2025-12-03 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_escolar_api', '0003_alumnos_maestros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nrc', models.CharField(max_length=255, unique=True)),
                ('nombre_materia', models.CharField(max_length=255)),
                ('seccion', models.CharField(max_length=3)),
                ('dias_semana', models.CharField(max_length=255)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('salon', models.CharField(max_length=15)),
                ('programa_educativo', models.CharField(max_length=255)),
                ('creditos', models.IntegerField()),
                ('creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('update', models.DateTimeField(blank=True, null=True)),
                ('profesor_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_escolar_api.maestros')),
            ],
        ),
    ]
